language: CSharp
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.sh | sh && source ~/.k/kvm/kvm.sh
  - npm install -g bower
  - npm install -g gulp
  - kvm upgrade
  - kpm restore --no-cache
script:
  - ./build.sh --quiet verify
